[{"content": "New chat started", "sender": "cloudChat"}]

[{"content": "New chat started", "sender": "cloudChat"},
 {"chats": [[Object]], "createdBy": "james@gmail.com", "id": "1718454525725_klym3hpdx", "link": "cloud/1718454525725", "receiver": "kevin "}, {"chats": [[Object]], "createdBy": "james@gmail.com", "id": "1718454555774_z8yiz7n0i", "link": "cloud/1718454555774", "receiver": "kevin "}, {"chats": [[Object]], "createdBy": "james@gmail.com", "id": "1718454570956_dxhsori8s", "link": "cloud/1718454570956", "receiver": "yelpoea "}]

